import type {
  DesignDiagramModelSpec,
  
  
  
  
  DesignRunSnapshot,
  DesignModelTraceabilityEntry,
  DesignSvgArtifact,
  DiagramError,
  DiagramModelSpec,
  DiagramVisualReview,
  RequirementModelTraceabilityEntry,
  RequirementBaseline,
  RequirementQualityReport,
  AtomicRequirement,
  RunSnapshot,
  RunStage,
  RunStatus as ContractRunStatus,
  SvgArtifact,
  ContextDiagramSpec,
  ContextTraceRow,
  FeasibilityImplementationPlan,
  FeasibilityInputs,
  FeasibilityBusinessFlowArtifact,
  TestGenerationResult,
} from "@uml-platform/contracts";
import type { DiagramType } from "../diagram/model";
import type { DesignDiagramType } from "../diagram/model";
import type { RequirementRule } from "../requirement-rule/model";

export type WorkspaceRunSnapshot = RunSnapshot;
export type WorkspaceDesignRunSnapshot = DesignRunSnapshot;

export type RunStatus = "idle" | ContractRunStatus;

export interface ManualModelEditStatus {
  status: "dirty" | "rerendered";
  warning: string | null;
  editedAt: string;
  rerenderedAt?: string;
}

export interface RequirementReviewCandidate {
  ruleId: string;
  beforeRequirement: AtomicRequirement;
  afterRequirement: AtomicRequirement | null;
  repairRationale: string | null;
  blockingReasons: string[];
  status: "pending" | "accepted" | "rejected" | "failed";
  errorMessage: string | null;
  createdAt: string;
}

export interface AutoGeneratedUpstreamReview {
  id: string;
  artifactType: "requirement-rule" | "requirement-model" | "design-model";
  artifactId: string;
  label: string;
  reason: string;
  sourceRunId: string | null;
  status: "pending" | "accepted" | "dismissed";
  createdAt: string;
}

export interface WorkspaceRecord {
  id: string;
  name: string;
  requirementText: string;
  selectedDiagramTypes: DiagramType[];
  rules: RequirementRule[];
  requirementBaseline: RequirementBaseline | null;
  requirementQualityReport: RequirementQualityReport | null;
  requirementReviewCandidates: Record<string, RequirementReviewCandidate>;
  autoGeneratedUpstreamReviews: Record<string, AutoGeneratedUpstreamReview>;
  models: Partial<Record<DiagramType, DiagramModelSpec>> &
    Record<string, DiagramModelSpec | undefined>;
  requirementModelTraceability: RequirementModelTraceabilityEntry[];
  generatedDiagramTypes: DiagramType[];
  plantUml: Partial<Record<DiagramType, string>> & Record<string, string | undefined>;
  svgArtifacts: Partial<Record<DiagramType, SvgArtifact>> &
    Record<string, SvgArtifact | undefined>;
  diagramErrors: Partial<Record<DiagramType, DiagramError>> &
    Record<string, DiagramError | undefined>;
  visualReviews?: Record<string, DiagramVisualReview>;
  selectedDesignDiagramTypes: DesignDiagramType[];
  designModels: Record<string, DesignDiagramModelSpec>;
  designModelTraceability: DesignModelTraceabilityEntry[];
  generatedDesignDiagramTypes: DesignDiagramType[];
  designPlantUml: Record<string, string>;
  designSvgArtifacts: Record<string, DesignSvgArtifact>;
  designDiagramErrors: Record<string, DiagramError>;
  manualModelEditStatus: Record<string, ManualModelEditStatus>;
  
  
  
  
  
  
  
  
  
  
  
  
  testGenerationResult: TestGenerationResult | null;
  requirementInputFingerprint: string | null;
  diagramInputFingerprints: Partial<Record<DiagramType, string>>;
  designInputFingerprints: Record<string, string>;
  feasibilityInputs: FeasibilityInputs;
  feasibilityContextModel: ContextDiagramSpec | null;
  feasibilityBusinessFlow: FeasibilityBusinessFlowArtifact | null;
  feasibilityContextTraceability: ContextTraceRow[];
  feasibilityContextPlantUml: string;
  feasibilityContextSvg: string;
  feasibilityContextFingerprint: string | null;
  feasibilityImplementationPlan: FeasibilityImplementationPlan | null;
  feasibilityImplementationFingerprint: string | null;
  rulesVersion: number;
  rulesBasedOnTextVersion: number | null;
  diagramVersions: Partial<Record<DiagramType, number>>;
  currentStage: RunStage | null;
  runStatus: RunStatus;
  runProgress: number;
  runMessage: string | null;
  errorMessage: string | null;
}
