// Defines the workspace repository contract shared by HTTP, mock, and React provider adapters.
import type {
  GenerationExecutionMode,
  UmlDiagramKind,
  
  DesignDiagramModelSpec,
  DesignRunSnapshot,
  DesignSvgArtifact,
  DiagramVisualReview,
  DiagramModelSpec,
  DocumentLibraryItem,
  DocumentRunSnapshot,
  OnlyOfficeEditorConfigResponse,
  OnlyOfficeUiTheme,
  RenderStructuredModelResponse,
  RenderSvgResponse,
  RepairRequirementRuleRequest,
  RepairRequirementRuleResponse,
  RepairRequirementRulesRequest,
  RepairRequirementRulesResponse,
  RequirementBaseline,
  RunEvent,
  RunSnapshot,
  SvgArtifact,
  FeasibilityRunSnapshot,
  FeasibilityInputs,
  FeasibilityImplementationPlan,
  ContextDiagramSpec,
  ContextTraceRow,
} from "@uml-platform/contracts";
import type { DiagramType } from "../../entities/diagram/model";
import type {
  ManualModelEditStatus,
  WorkspaceRecord,
} from "../../entities/workspace/model";
import type { RequirementRule } from "../../entities/requirement-rule/model";
import type {
  RunHistoryItem,
  RunHistorySnapshot,
} from "../../entities/run-history";
import type { ModelCapability } from "../../shared/lib/provider-model-display";
import type {
  ProviderSettingsInput,
  
  StartDesignRunInput,
  StartDocumentRunInput,
  StartFeasibilityRunInput,
  StartRunInput,
} from "./start-inputs";

export interface RequirementRulesUpdateMetadata {
  sourceRunId?: string;
  requirementBaseline?: WorkspaceRecord["requirementBaseline"];
  requirementInputFingerprint?: string | null;
  requirementModelTraceability?: WorkspaceRecord["requirementModelTraceability"];
  requirementQualityReport?: WorkspaceRecord["requirementQualityReport"];
  requirementReviewCandidates?: WorkspaceRecord["requirementReviewCandidates"];
  rulesBasedOnTextVersion?: number | null;
  rulesVersion?: number;
}

// Recovery delivers snapshots independently of SSE events, including partial results.
export interface RunSubscriptionOptions<TSnapshot> {
  signal?: AbortSignal;
  onSnapshot?: (snapshot: TSnapshot) => void | Promise<void>;
}

export interface WorkspaceRepository {
  exportDiagram?(input: { diagramKind: UmlDiagramKind; plantUmlSource: string; format: "png" | "pdf" }, signal?: AbortSignal): Promise<Blob>;
  loadWorkspace(): Promise<WorkspaceRecord>;
  getProjectAccess?(): Promise<{
    capabilities: string[];
    generationExecutionMode?: GenerationExecutionMode;
  }>;
  updateRequirementText(text: string): Promise<void>;
  updateFeasibility?(patch: Partial<{
    inputs: FeasibilityInputs;
    contextModel: ContextDiagramSpec | null;
    contextTraceability: ContextTraceRow[];
    contextPlantUml: string;
    contextSvg: string;
    contextFingerprint: string | null;
    implementationPlan: FeasibilityImplementationPlan | null;
    implementationFingerprint: string | null;
  }>): Promise<void>;
  startFeasibilityRun?(input: StartFeasibilityRunInput): Promise<{ runId: string }>;
  getFeasibilityRunSnapshot?(runId: string): Promise<FeasibilityRunSnapshot>;
  subscribeToFeasibilityRun?(
    runId: string,
    onEvent: (event: RunEvent) => void,
    options?: RunSubscriptionOptions<FeasibilityRunSnapshot>,
  ): Promise<void>;
  updateRequirementRules?(
    rules: RequirementRule[],
    metadata?: RequirementRulesUpdateMetadata,
  ): Promise<void>;
  updateRequirementBaseline?(baseline: RequirementBaseline): Promise<void>;
  updateRequirementReviewCandidates?(
    candidates: WorkspaceRecord["requirementReviewCandidates"],
    options?: { sourceRunId?: string },
  ): Promise<void>;
  updateAutoGeneratedUpstreamReviews?(
    reviews: WorkspaceRecord["autoGeneratedUpstreamReviews"],
  ): Promise<void>;
  
  updateTestGenerationResult?(
    result: WorkspaceRecord["testGenerationResult"],
  ): Promise<void>;
  updateRequirementReviewState?(
    baseline: RequirementBaseline,
    candidates: WorkspaceRecord["requirementReviewCandidates"],
  ): Promise<void>;
  confirmVisualReview?(key: string, checkedAt: string): Promise<DiagramVisualReview>;
  confirmVisualReview?(key: string, checkedAt: string): Promise<DiagramVisualReview>;
  repairRequirementRule?(
    input: RepairRequirementRuleRequest,
  ): Promise<RepairRequirementRuleResponse>;
  repairRequirementRules?(
    input: RepairRequirementRulesRequest,
  ): Promise<RepairRequirementRulesResponse>;
  startRun(input: StartRunInput): Promise<{ runId: string }>;
  startDesignRun?(input: StartDesignRunInput): Promise<{ runId: string }>;
  
  startDocumentRun?(input: StartDocumentRunInput): Promise<{ runId: string }>;
  subscribeToRun(
    runId: string,
    onEvent: (event: RunEvent) => void,
    options?: RunSubscriptionOptions<RunSnapshot>,
  ): Promise<void>;
  subscribeToDesignRun?(
    runId: string,
    onEvent: (event: RunEvent) => void,
    options?: RunSubscriptionOptions<DesignRunSnapshot>,
  ): Promise<void>;
  
  subscribeToDocumentRun?(
    runId: string,
    onEvent: (event: RunEvent) => void,
    options?: RunSubscriptionOptions<DocumentRunSnapshot>,
  ): Promise<void>;
  getRunSnapshot(runId: string): Promise<RunSnapshot>;
  getDesignRunSnapshot?(runId: string): Promise<DesignRunSnapshot>;
  
  getDocumentRunSnapshot?(runId: string): Promise<DocumentRunSnapshot>;
  listDocuments?(): Promise<DocumentLibraryItem[]>;
  getOnlyOfficeEditorConfig?(
    documentId: string,
    uiTheme?: OnlyOfficeUiTheme,
  ): Promise<OnlyOfficeEditorConfigResponse>;
  downloadDocumentRun?(
    runId: string,
    defaultFileName?: string,
  ): Promise<{ blob: Blob; fileName: string }>;
  downloadDocument?(
    documentId: string,
    defaultFileName?: string,
  ): Promise<{ blob: Blob; fileName: string }>;
  renderPlantUml(
    diagramKind: DiagramType,
    plantUmlSource: string,
  ): Promise<RenderSvgResponse>;
  renderStructuredModel?(
    model: DiagramModelSpec | DesignDiagramModelSpec,
    stage: "feasibility" | "requirements" | "design",
  ): Promise<RenderStructuredModelResponse>;
  saveRequirementModelEdit?(
    diagramKind: DiagramType,
    model: DiagramModelSpec,
    status: ManualModelEditStatus,
    traceability?: Pick<
      WorkspaceRecord,
      "requirementModelTraceability" | "designModelTraceability"
    >,
  ): Promise<void>;
  saveDesignModelEdit?(
    modelId: string,
    model: DesignDiagramModelSpec,
    status: ManualModelEditStatus,
    traceability?: Pick<WorkspaceRecord, "designModelTraceability">,
  ): Promise<void>;
  saveManualModelRerender?(
    key: string,
    status: ManualModelEditStatus,
    artifact: {
      plantUmlSource: string;
      svgArtifact: SvgArtifact | DesignSvgArtifact;
    },
  ): Promise<void>;
  testProviderSettings(providerSettings: ProviderSettingsInput): Promise<{
    ok: boolean;
    message: string;
    capability: ModelCapability;
  }>;
  saveRunHistory(
    snapshot: RunHistorySnapshot,
    meta: { providerModel: string; durationMs?: number },
  ): Promise<RunHistoryItem>;
  listRunHistory(): Promise<RunHistoryItem[]>;
  getRunHistoryItem?(id: string): Promise<RunHistoryItem | null>;
  restoreRunHistory(id: string): Promise<RunHistoryItem | null>;
  deleteRunHistory(id: string): Promise<RunHistoryItem[]>;
  clearRunHistory(): Promise<void>;
}
