// Keeps requirement-model card details accessible without expanding dense card content inline.
import { Eye, WandSparkles } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import type { RequirementRule } from "../../../entities/requirement-rule/model";
import { Badge } from "../../../shared/ui/badge";
import { Button } from "../../../shared/ui/button";
import {
  Popover,
  PopoverContent,
  PopoverDescription,
  PopoverTitle,
  PopoverTrigger,
} from "../../../shared/ui/popover";
import { mobileTouchTargetClass } from "../../workspace-shell/components/mobile-density";
import type { AutoGeneratedUpstreamReview } from "../lib/requirement-review-view-model";

const categoryKey = (category: RequirementRule["category"]) =>
  ({
    业务规则: "business",
    功能需求: "functional",
    外部接口: "externalInterface",
    界面需求: "interface",
    数据需求: "data",
    非功能需求: "nonFunctional",
    部署需求: "deployment",
    异常处理: "exception",
  })[category];

type RequirementModelCardPopoversProps = {
  autoFillLabels: string[];
  label: string;
  linkedRules: RequirementRule[];
  pendingAutoReviews: AutoGeneratedUpstreamReview[];
  onDecideAutoReviews: (
    reviews: AutoGeneratedUpstreamReview[],
    decision: "accepted" | "dismissed",
  ) => void;
  onLocateRule: (ruleId: string) => void;
  showRuleLocations: boolean;
};

export function RequirementModelCardPopovers({
  autoFillLabels,
  label,
  linkedRules,
  pendingAutoReviews,
  onDecideAutoReviews,
  onLocateRule,
  showRuleLocations,
}: RequirementModelCardPopoversProps) {
  const { t } = useTranslation();
  const [openDetail, setOpenDetail] = useState<"auto-fill" | "rules" | null>(null);
  const hasAutoFillDetails =
    autoFillLabels.length > 0 || pendingAutoReviews.length > 0;

  if (!hasAutoFillDetails && linkedRules.length === 0) return null;

  return (
    <div className="flex flex-wrap items-center gap-1.5">
      {hasAutoFillDetails && (
        <Popover
          open={openDetail === "auto-fill"}
          onOpenChange={(open) =>
            setOpenDetail((current) =>
              open ? "auto-fill" : current === "auto-fill" ? null : current,
            )
          }
        >
          <PopoverTrigger
            render={
              <Button
                type="button"
                size="icon-xs"
                variant="ghost"
                className="text-warning hover:text-warning"
                aria-label={t("requirements.autoFillDetailsAria", { label })}
                title={t("requirements.autoFillDetailsAria", { label })}
              />
            }
            onClick={(event) => event.stopPropagation()}
            onKeyDown={(event) => event.stopPropagation()}
          >
            <WandSparkles className="size-3.5" />
          </PopoverTrigger>
          <PopoverContent
            align="start"
            side="bottom"
            className="w-80 sm:w-96"
            onClick={(event) => event.stopPropagation()}
            onKeyDown={(event) => event.stopPropagation()}
          >
            <PopoverTitle>{t("requirements.autoFillDetailsTitle", { label })}</PopoverTitle>
            <PopoverDescription>
              {t("requirements.autoFillDescription")}
            </PopoverDescription>
            <div className="mt-3 grid max-h-[min(60vh,24rem)] gap-2 overflow-y-auto pr-1">
              {autoFillLabels.length > 0 && (
                <div className="rounded-md border border-warning/30 bg-warning/5 px-3 py-2 text-xs leading-5 text-foreground">
                  {t("requirements.willAutoFill", {
                    labels: autoFillLabels.join(t("traceability.refSeparator")),
                  })}
                </div>
              )}
              {pendingAutoReviews.map((review) => (
                <div
                  key={review.id}
                  className="rounded-md border border-border bg-muted/30 px-3 py-2 text-xs leading-5"
                >
                  <div className="font-medium text-foreground">{review.label}</div>
                  <div className="mt-1 text-muted-foreground">{review.reason}</div>
                </div>
              ))}
            </div>
            {pendingAutoReviews.length > 0 && (
              <div className="mt-3 flex flex-wrap justify-end gap-2 border-t border-border pt-3">
                <Button
                  type="button"
                  size="sm"
                  variant="ghost"
                  aria-label={t("requirements.dismissAutoFillAria", { label })}
                  onClick={(event) => {
                    event.stopPropagation();
                    onDecideAutoReviews(pendingAutoReviews, "dismissed");
                  }}
                >
                  {t("requirements.dismissAutoFill")}
                </Button>
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  aria-label={t("requirements.acceptAutoFillAria", { label })}
                  onClick={(event) => {
                    event.stopPropagation();
                    onDecideAutoReviews(pendingAutoReviews, "accepted");
                  }}
                >
                  {t("requirements.acceptAutoFill")}
                </Button>
              </div>
            )}
          </PopoverContent>
        </Popover>
      )}

      {linkedRules.length > 0 && (
        <Popover
          open={openDetail === "rules"}
          onOpenChange={(open) =>
            setOpenDetail((current) =>
              open ? "rules" : current === "rules" ? null : current,
            )
          }
        >
          <PopoverTrigger
            render={
              <Button
                type="button"
                variant="ghost"
                className={`inline-flex items-center gap-1 px-2 py-1 text-[11px] ${mobileTouchTargetClass} sm:min-h-0`}
                aria-label={t("requirements.relatedRulesAria", { label })}
              />
            }
            onClick={(event) => event.stopPropagation()}
            onKeyDown={(event) => event.stopPropagation()}
          >
            <Eye className="size-3" />
            {t("requirements.viewRelatedRules")}
          </PopoverTrigger>
          <PopoverContent
            align="start"
            side="bottom"
            className="w-80 sm:w-96"
            onClick={(event) => event.stopPropagation()}
            onKeyDown={(event) => event.stopPropagation()}
          >
            <PopoverTitle>{t("requirements.relatedRulesTitle", { label })}</PopoverTitle>
            <PopoverDescription>
              {t("requirements.relatedRulesCount", { count: linkedRules.length })}
            </PopoverDescription>
            <div className="mt-3 grid max-h-[min(60vh,24rem)] gap-2 overflow-y-auto pr-1">
              {linkedRules.map((rule) => {
                const content = (
                  <>
                    <span className="flex flex-wrap items-center gap-2">
                      <span className="font-mono text-[11px] font-semibold uppercase text-foreground">
                        {rule.id}
                      </span>
                      <Badge variant="outline" className="px-1.5 py-0 text-[10px]">
                        {t(`requirements.categories.${categoryKey(rule.category)}`)}
                      </Badge>
                    </span>
                    <span className="mt-1 block whitespace-normal text-left text-xs leading-5 text-muted-foreground">
                      {rule.text}
                    </span>
                  </>
                );

                return showRuleLocations ? (
                  <Button
                    key={rule.id}
                    type="button"
                    variant="ghost"
                    className="h-auto min-w-0 justify-start whitespace-normal rounded-md border border-border px-3 py-2"
                    aria-label={t("requirements.relatedRuleLocateAria", { id: rule.id })}
                    onClick={(event) => {
                      event.stopPropagation();
                      onLocateRule(rule.id);
                    }}
                  >
                    <span className="block min-w-0 text-left">{content}</span>
                  </Button>
                ) : (
                  <div
                    key={rule.id}
                    className="rounded-md border border-border bg-muted/30 px-3 py-2"
                  >
                    {content}
                  </div>
                );
              })}
            </div>
          </PopoverContent>
        </Popover>
      )}
    </div>
  );
}
