// Renders the requirement authoring page and coordinates rule editing, quality checks, and generation actions.
import { Alert } from '../../../shared/ui/alert';
import { Card } from "../../../shared/ui/card";
import { Textarea } from '../../../shared/ui/textarea';
import { useEffect, useMemo, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import {
  Wand2,
  Loader2,
  AlertTriangle,
  RefreshCw,
  ArrowUp,
  FileText,
  ListChecks,
  Network,
  Box,
  Server,
  GitBranch,
  Activity,
  Eye,
  X,
} from "lucide-react";
import { Button } from "../../../shared/ui/button";
import { Badge } from "../../../shared/ui/badge";
import { cn } from "../../../shared/ui/utils";
import type {
  AtomicRequirement,
  AtomicRequirementField,
  RequirementQualityIssue,
} from "@uml-platform/contracts";
import {
  DIAGRAM_META,
  DIAGRAM_ORDER,
  getDiagramDescription,
  getDiagramLabel,
  type DiagramType,
} from "../../../entities/diagram/model";
import {
  type RequirementRule,
} from "../../../entities/requirement-rule/model";
import { useWorkspaceSession } from "../../workspace-session/state";
import {
  buildRequirementModelRepairRecords,
  requirementDiagramsButtonLabel,
  requirementTargetBlockReason,
  requirementTargetCardState,
} from "../lib/requirement-target-view-model";
import {
  requirementRowState,
  type AutoGeneratedUpstreamReview,
} from "../lib/requirement-review-view-model";
import { ModelPicker } from "../../../shared/ui/model-picker";
import {
  EmptyState,
  PageContainer,
  PageHeader,
} from "../../../shared/template/layout/page";
import {
  loadUserSettings,
  patchUserSettings,
  USER_SETTINGS_CHANGED_EVENT,
} from "../../../shared/lib/user-settings";
import {
  MobileCompactGrid,
} from "../../workspace-shell/components/mobile-density";
import { ModelBentoCard } from "../../workspace-shell/components/model-bento-card";
import { useModelCardStatus } from "../../workspace-shell/lib/use-model-card-status";
import {
  ALL_RULE_CATEGORIES,
  REQUIREMENT_RULES_PER_PAGE,
  RequirementRulesTable,
  type RequirementRuleCategoryFilter,
} from "./requirement-rules-table";
import {
  RequirementReviewDialog,
  type RequirementHintDetail,
} from "./requirement-review-dialog";
import {
  RequirementTraceabilityDialogs,
  type RequirementModelRepairResult,
} from "./requirement-traceability-dialogs";
import { NewRequirementRuleDialog } from "./new-requirement-rule-dialog";
import { RequirementModelCardPopovers } from "./requirement-model-card-popovers";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "../../../shared/ui/dialog";

const DEFAULT_NEW_RULE_DIAGRAMS: DiagramType[] = ["function", "usecase", "activity"];
const REQUIREMENT_DIAGRAM_ICON = {
  context: Network,
  function: FileText,
  usecase: Network,
  activity: Activity,
  class: Box,
  deployment: Server,
  prototype: Eye,
  analysis: GitBranch,
} satisfies Record<DiagramType, typeof Network>;

export function TextRequirementView({
  view = "all",
}: {
  view?: "system" | "models" | "all";
}) {
  const { t } = useTranslation();
  const { requirementStatusFor } = useModelCardStatus();
  const {
    requirementText,
    setRequirementText,
    rules,
    createRequirementRule,
    updateRequirementRule,
    deleteRequirementRule,
    selectedDiagrams,
    setSelectedDiagrams,
    generating,
    generateRules,
    generateDiagrams,
    isRulesStale,
    rulesStaleReason,
    staleDiagrams,
    generatedDiagrams,
    requirementModelTraceability,
    autoGeneratedUpstreamReviews,
    decideAutoGeneratedUpstreamReview,
    requirementBaseline,
    requirementReviewCandidates,
    requirementReviewBlockedReason,
    repairRequirementRule,
    decideRequirementReviewCandidate,
    confirmRequirementQualityHint,
    canUpdateWorkspace,
    canStartRuns,
    workspacePermissionReason,
    billingGenerationBlock,
    clearBillingGenerationBlock,
  } = useWorkspaceSession();
  const [query, setQuery] = useState("");
  const [defaultModel, setDefaultModel] = useState(
    () => loadUserSettings().defaultModel,
  );
  const [showStaleBanner, setShowStaleBanner] = useState(
    () => loadUserSettings().showStaleBanner,
  );
  const [newRuleDialogOpen, setNewRuleDialogOpen] = useState(false);
  const [newRuleCategory, setNewRuleCategory] =
    useState<RequirementRule["category"]>("功能需求");
  const [newRuleDiagrams, setNewRuleDiagrams] = useState<DiagramType[]>(
    DEFAULT_NEW_RULE_DIAGRAMS,
  );
  const [newRuleText, setNewRuleText] = useState("");
  const [newRuleError, setNewRuleError] = useState<string | null>(null);
  const [modelRepairResult, setModelRepairResult] =
    useState<RequirementModelRepairResult | null>(null);
  const [hintDetailRuleId, setHintDetailRuleId] = useState<string | null>(null);
  const [traceabilityDialogOpen, setTraceabilityDialogOpen] = useState(false);
  const [ruleReplacementDialogOpen, setRuleReplacementDialogOpen] =
    useState(false);
  const [currentRulePage, setCurrentRulePage] = useState(1);
  const [rulePageSize, setRulePageSize] = useState(REQUIREMENT_RULES_PER_PAGE);
  const [ruleCategoryFilter, setRuleCategoryFilter] =
    useState<RequirementRuleCategoryFilter>(ALL_RULE_CATEGORIES);

  useEffect(() => {
    const syncSettings = () => {
      const settings = loadUserSettings();
      setDefaultModel(settings.defaultModel);
      setShowStaleBanner(settings.showStaleBanner);
    };

    window.addEventListener(USER_SETTINGS_CHANGED_EVENT, syncSettings);
    return () => {
      window.removeEventListener(USER_SETTINGS_CHANGED_EVENT, syncSettings);
    };
  }, []);

  const hasGeneratedRules = rules.length > 0;
  const hasRequirementSourceText = requirementText.trim().length > 0;
  const canEditRequirements = canUpdateWorkspace;
  const canRunGeneration = canUpdateWorkspace && canStartRuns;
  const editBlockedReason =
    workspacePermissionReason ?? t("requirements.permissions.edit");
  const generationBlockedByPermissionReason =
    workspacePermissionReason ?? t("requirements.permissions.run");

  const runGenerateRules = () => {
    if (!canRunGeneration) return;
    if (hasGeneratedRules) {
      setRuleReplacementDialogOpen(true);
      return;
    }
    void generateRules();
  };

  const confirmRuleReplacement = () => {
    setRuleReplacementDialogOpen(false);
    if (!canRunGeneration) return;
    void generateRules();
  };

  const runGenerateDiagrams = (only?: DiagramType[]) => {
    if (!canRunGeneration) return;
    void generateDiagrams(only);
  };

  const decideAutoReviews = (
    reviews: AutoGeneratedUpstreamReview[],
    decision: "accepted" | "dismissed",
  ) => {
    void Promise.all(
      reviews.map((review) =>
        decideAutoGeneratedUpstreamReview(review.id, decision),
      ),
    );
  };

  const locateRequirementRule = (ruleId: string) => {
    const element = document.getElementById(`rule-${ruleId}`);
    if (!element) return;
    element.scrollIntoView({ behavior: "smooth", block: "center" });
    element.classList.add("ring-2", "ring-primary/40");
    setTimeout(() => {
      element.classList.remove("ring-2", "ring-primary/40");
    }, 1200);
  };

  const updateModel = (model: string) => {
    if (!canRunGeneration) return;
    patchUserSettings({ defaultModel: model });
  };

  const selectableDiagramSet = useMemo(() => new Set(DIAGRAM_ORDER), []);

  const toggleDiagram = (diagram: DiagramType, checked: boolean) => {
    if (!canEditRequirements) return;
    if (checked && !selectableDiagramSet.has(diagram)) {
      return;
    }
    setSelectedDiagrams(
      checked
        ? Array.from(new Set([...selectedDiagrams, diagram]))
        : selectedDiagrams.filter((value) => value !== diagram),
    );
  };

  useEffect(() => {
    const nextSelectedDiagrams = selectedDiagrams.filter((diagram) =>
      selectableDiagramSet.has(diagram),
    );
    if (nextSelectedDiagrams.length !== selectedDiagrams.length) {
      setSelectedDiagrams(nextSelectedDiagrams);
    }
  }, [selectableDiagramSet, selectedDiagrams, setSelectedDiagrams]);

  const toggleNewRuleDiagram = (diagram: DiagramType, checked: boolean) => {
    setNewRuleDiagrams((current) =>
      checked
        ? Array.from(new Set([...current, diagram]))
        : current.filter((value) => value !== diagram),
    );
  };

  const resetNewRuleForm = () => {
    setNewRuleCategory("功能需求");
    setNewRuleDiagrams(DEFAULT_NEW_RULE_DIAGRAMS);
    setNewRuleText("");
    setNewRuleError(null);
  };

  const submitNewRule = () => {
    const trimmedText = newRuleText.trim();
    if (!trimmedText) {
      setNewRuleError(t("requirements.validation.textRequired"));
      return;
    }
    if (newRuleDiagrams.length === 0) {
      setNewRuleError(t("requirements.validation.modelRequired"));
      return;
    }
    createRequirementRule({
      category: newRuleCategory,
      relatedDiagrams: newRuleDiagrams,
      text: trimmedText,
    });
    setNewRuleDialogOpen(false);
    resetNewRuleForm();
  };

  const newRuleCanSubmit = newRuleText.trim().length > 0 && newRuleDiagrams.length > 0;

  const filteredRules = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    return rules.filter((rule) => {
      const matchesQuery =
        !normalizedQuery || rule.text.toLowerCase().includes(normalizedQuery);
      const matchesCategory =
        ruleCategoryFilter === ALL_RULE_CATEGORIES ||
        rule.category === ruleCategoryFilter;
      return matchesQuery && matchesCategory;
    });
  }, [rules, query, ruleCategoryFilter]);

  useEffect(() => {
    setCurrentRulePage(1);
  }, [query, ruleCategoryFilter]);

  const totalRulePages = Math.max(1, Math.ceil(filteredRules.length / rulePageSize));
  const safeRulePage = Math.min(currentRulePage, totalRulePages);
  const firstRuleIndex =
    filteredRules.length === 0 ? 0 : (safeRulePage - 1) * rulePageSize + 1;
  const lastRuleIndex = Math.min(filteredRules.length, safeRulePage * rulePageSize);
  const pagedRules = filteredRules.slice(firstRuleIndex - 1, lastRuleIndex);
  const emptyRuleSlots = Math.max(0, rulePageSize - pagedRules.length);
  const requirementByRuleId = useMemo(() => {
    const entries =
      requirementBaseline?.requirements
        .filter((requirement) => requirement.sourceRuleId)
        .map((requirement) => [requirement.sourceRuleId!, requirement] as const) ?? [];
    return new Map(entries);
  }, [requirementBaseline]);
  const qualityIssuesByRequirementId = useMemo(() => {
    const map = new Map<string, RequirementQualityIssue[]>();
    for (const issue of requirementBaseline?.qualityReport.issues ?? []) {
      if (!issue.requirementId) continue;
      map.set(issue.requirementId, [
        ...(map.get(issue.requirementId) ?? []),
        issue,
      ]);
    }
    return map;
  }, [requirementBaseline]);
  const hintDetail = useMemo<RequirementHintDetail | null>(() => {
    if (!hintDetailRuleId) return null;
    const rule = rules.find((item) => item.id === hintDetailRuleId);
    const requirement = requirementByRuleId.get(hintDetailRuleId);
    if (!rule || !requirement) return null;
    const qualityIssues = qualityIssuesByRequirementId.get(requirement.id) ?? [];
    const fieldEntries = Object.entries(requirement.fieldProvenance).filter(
      (entry): entry is [
        AtomicRequirementField,
        NonNullable<AtomicRequirement["fieldProvenance"][AtomicRequirementField]>,
      ] => {
        const [, provenance] = entry;
        return Boolean(
          provenance &&
            (provenance.source === "ai-suggested" ||
              provenance.status === "pending-review" ||
              provenance.status === "rejected"),
        );
      },
    );
    return {
      rule,
      requirement,
      candidate: requirementReviewCandidates[hintDetailRuleId] ?? null,
      rowState: requirementRowState(requirement, qualityIssues),
      qualityIssues,
      fieldEntries,
    };
  }, [
    hintDetailRuleId,
    qualityIssuesByRequirementId,
    requirementByRuleId,
    requirementReviewCandidates,
    rules,
  ]);
  const lastHintDetailRef = useRef<typeof hintDetail>(null);
  if (hintDetail) {
    lastHintDetailRef.current = hintDetail;
  }
  const visibleHintDetail = hintDetailRuleId
    ? hintDetail ??
      (lastHintDetailRef.current?.rule.id === hintDetailRuleId
        ? lastHintDetailRef.current
        : null)
    : null;
  useEffect(() => {
    if (currentRulePage > totalRulePages) {
      setCurrentRulePage(totalRulePages);
    }
  }, [currentRulePage, totalRulePages]);

  const generateDiagramsButtonLabel = requirementDiagramsButtonLabel({
    generatedDiagrams,
    selectedDiagrams,
    staleDiagrams,
    t,
  });
  const visibleRequirementReviewBlockedReason = requirementReviewBlockedReason
    ? t("requirements.reviewBlocked")
    : null;
  const generationBlockedTitle =
    visibleRequirementReviewBlockedReason ?? undefined;
  const selectedTargetBlockReason =
    selectedDiagrams
      .map((diagram) =>
        requirementTargetBlockReason({
          diagram,
          generatedDiagrams,
          hasRequirementSourceText,
          isRulesStale,
          rules,
          staleDiagrams,
        }),
      )
      .find(Boolean) ?? null;
  const requirementModelRepairRecords = useMemo(() => {
    return buildRequirementModelRepairRecords({
      generatedDiagrams,
      requirementModelTraceability,
      rules,
    });
  }, [generatedDiagrams, requirementModelTraceability, rules]);
  const rulesStaleMessage =
    rulesStaleReason === "rules"
      ? t("requirements.stale.downstream")
      : rulesStaleReason === "source-missing"
        ? t("requirements.stale.empty")
        : t("requirements.stale.changed");
  const staleDiagramReason =
    isRulesStale && rulesStaleReason === "text"
      ? t("requirements.stale.changedTitle")
      : rulesStaleReason === "source-missing"
        ? t("requirements.stale.emptyTitle")
      : t("requirements.stale.reviewTitle");

  const renderRequirementInput = (mode: "empty" | "generated") => {
    // Keep the input mounted when loaded rules change the surrounding section presentation.
    return <Card
      className={cn(
        "gap-0 py-0 relative",
        mode === "generated" && "block overflow-visible rounded-none bg-transparent shadow-none ring-0",
        mode === "empty" &&
          "gap-0 overflow-hidden p-4 py-0 sm:p-6 sm:py-0",
      )}
    >
      <div className="relative flex items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <FileText className="size-5 text-primary" />
          <h2
            id="requirement-text-heading"
            className="text-xl font-semibold tracking-normal text-foreground"
          >
            {mode === "empty" ? t("requirements.source.projectDescription") : t("requirements.source.description")}
          </h2>
        </div>
      </div>
      <Textarea
        id="requirement-text"
        aria-labelledby="requirement-text-heading"
        name="requirementText"
        value={requirementText}
        onChange={(event) => {
          if (canEditRequirements) setRequirementText(event.target.value);
        }}
        placeholder={t("requirements.source.placeholder")}
        disabled={!canEditRequirements}
        title={!canEditRequirements ? editBlockedReason : undefined}
        className={cn(
          "relative mt-3 w-full resize-y border px-4 py-4 text-sm leading-relaxed",
          !canEditRequirements &&
            "cursor-not-allowed",
          mode === "empty" ? "min-h-80" : "min-h-[240px]",
        )}
      />
      <div data-testid="requirements-input-toolbar" className="relative mt-6 flex min-w-0 flex-nowrap items-center gap-2">
          <ModelPicker
            value={defaultModel}
            onValueChange={updateModel}
            disabled={!canRunGeneration}
          />
          {isRulesStale && (
            <Badge variant="secondary" className="hidden px-1.5 py-0 text-[11px] sm:inline-flex">
              {t("requirements.source.changed")}
            </Badge>
          )}
          <div className="ml-auto flex min-w-0 flex-1 items-center justify-end gap-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="h-10 shrink-0 px-3 sm:px-6"
              onClick={() => setRequirementText("")}
              disabled={!requirementText || generating || !canEditRequirements}
              title={!canEditRequirements ? editBlockedReason : undefined}
            >
              {t("requirements.source.clear")}
            </Button>
            <Button
              type="button"
              onClick={runGenerateRules}
              disabled={!requirementText.trim() || generating || !canRunGeneration}
              title={
                !canRunGeneration
                  ? generationBlockedByPermissionReason
                  : isRulesStale
                    ? t("requirements.source.updateRules")
                    : t("requirements.source.generateRules")
              }
              className="inline-flex h-10 min-w-0 flex-1 items-center gap-2 px-2 text-sm hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40 sm:flex-none sm:px-6"
            >
              {generating ? (
                <Loader2 className="size-4 animate-spin" />
              ) : (
                <ArrowUp className="size-4" />
              )}
              <span className="min-w-0 truncate">{isRulesStale ? t("requirements.source.updateRules") : t("requirements.source.startAnalysis")}</span>
            </Button>
          </div>
      </div>
    </Card>;
  };

  const renderRequirementRules = () => (
    <RequirementRulesTable
      canEditRequirements={canEditRequirements}
      currentRulePage={currentRulePage}
      deleteRequirementRule={deleteRequirementRule}
      editBlockedReason={editBlockedReason}
      emptyRuleSlots={emptyRuleSlots}
      filteredRules={filteredRules}
      firstRuleIndex={firstRuleIndex}
      generating={generating}
      lastRuleIndex={lastRuleIndex}
      onAddRule={() => setNewRuleDialogOpen(true)}
      onOpenHintDetail={setHintDetailRuleId}
      pagedRules={pagedRules}
      qualityIssuesByRequirementId={qualityIssuesByRequirementId}
      query={query}
      requirementByRuleId={requirementByRuleId}
      requirementReviewCandidates={requirementReviewCandidates}
      ruleCategoryFilter={ruleCategoryFilter}
      rulePageSize={rulePageSize}
      rulesCount={rules.length}
      safeRulePage={safeRulePage}
      setCurrentRulePage={setCurrentRulePage}
      setQuery={setQuery}
      setRuleCategoryFilter={setRuleCategoryFilter}
      setRulePageSize={setRulePageSize}
      totalRulePages={totalRulePages}
      updateRequirementRule={updateRequirementRule}
    />
  );

  return (
    <div className="flex min-h-0 min-w-0 max-w-full flex-col overflow-x-clip bg-background">
      {view !== "models" && showStaleBanner && isRulesStale && (
        <div className="flex items-center gap-2 border-b border-warning/40 bg-warning/10 px-3 py-2 text-sm">
          <AlertTriangle className="size-4 text-warning" />
          <span>{rulesStaleMessage}</span>
          <Button
            size="sm"
            variant="outline"
            className="ml-auto h-7"
            onClick={runGenerateRules}
            disabled={generating || !canRunGeneration}
            title={!canRunGeneration ? generationBlockedByPermissionReason : undefined}
          >
            <RefreshCw className="size-3.5" /> {t("requirements.source.regenerateRules")}
          </Button>
        </div>
      )}

      {view !== "system" && showStaleBanner && staleDiagrams.length > 0 && (
        <div className="flex items-center gap-2 border-b border-warning/40 bg-warning/10 px-3 py-2 text-sm">
          <AlertTriangle className="size-4 text-warning" />
          <span>
            {t("requirements.stale.modelCount", { count: staleDiagrams.length, reason: staleDiagramReason })}
            {staleDiagrams.map((diagram) => getDiagramLabel(diagram, t)).join(t("traceability.refSeparator"))}
          </span>
          <Button
            size="sm"
            variant="outline"
            className="ml-auto h-7"
            onClick={() => runGenerateDiagrams(staleDiagrams)}
            disabled={
              generating ||
              Boolean(requirementReviewBlockedReason) ||
              !canRunGeneration
            }
            title={
              !canRunGeneration
                ? generationBlockedByPermissionReason
                : generationBlockedTitle
            }
          >
            <RefreshCw className="size-3.5" /> {t("requirements.stale.updateModels")}
          </Button>
        </div>
      )}

      <PageContainer className="flex flex-col gap-5">
          <PageHeader
            title={
              view === "system"
                ? t("requirements.page.systemTitle")
                : view === "models"
                  ? t("requirements.page.modelsTitle")
                  : t("requirements.page.allTitle")
            }
            description={
              view === "system"
                ? t("requirements.page.systemDescription")
                : view === "models"
                  ? t("requirements.page.modelsDescription")
                  : t("requirements.page.allDescription")
            }
          />
          {!canEditRequirements && (
            <Alert className="inline-flex max-w-3xl items-center gap-2 border px-3 py-2 text-xs">
              <AlertTriangle className="size-3.5" />
              {editBlockedReason}
            </Alert>
          )}
          {billingGenerationBlock && (
            <Alert className="flex max-w-4xl flex-wrap items-center gap-3 border px-3 py-2 text-sm text-foreground">
              <AlertTriangle className="size-4 text-warning" />
              <div className="min-w-0 flex-1">
                <div className="font-medium">{billingGenerationBlock.message}</div>
                <div className="text-xs text-muted-foreground">
                  {t("requirements.credits", { count: billingGenerationBlock.billingSummary.creditBalance })}
                </div>
              </div>
              <Button
                type="button"
                size="icon"
                variant="ghost"
                className="size-8"
                aria-label={t("requirements.closeCredits")}
                onClick={clearBillingGenerationBlock}
              >
                <X className="size-4" />
              </Button>
            </Alert>
          )}
          {view !== "models" && <div className="grid min-w-0 max-w-full grid-cols-1 gap-4 overflow-x-hidden">
            <div className="grid min-w-0 grid-cols-[minmax(0,1fr)] gap-4">
              {renderRequirementInput(hasGeneratedRules ? "generated" : "empty")}
              {hasGeneratedRules && renderRequirementRules()}
            </div>
          </div>}

          {view === "models" && rules.length === 0 && (
            <EmptyState icon={ListChecks} title={t("requirements.noRules")} />
          )}

          {view !== "system" && <section className="flex min-w-0 flex-col gap-4">
            <div className="flex min-w-0 flex-col items-stretch gap-3 sm:flex-row sm:items-center sm:justify-between sm:gap-2">
              <div className="flex min-w-0 flex-wrap items-center gap-2">
                <Network className="size-5 text-primary" />
                <h2 className="text-xl font-semibold tracking-normal text-foreground">
                  {t("requirements.targetModels")}
                </h2>
                <Badge
                  variant="secondary"
                  className="border-0 px-3 py-1 font-mono text-xs"
                >
                  {selectedDiagrams.length}/{DIAGRAM_ORDER.length}
                </Badge>
              </div>
              <div className="flex min-w-0 flex-nowrap items-center gap-2 overflow-x-auto pb-1 sm:shrink-0 sm:overflow-visible sm:pb-0">
                {requirementModelRepairRecords.length > 0 && (
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    className="h-9"
                    aria-label={t("requirements.traceProofAria", { count: requirementModelRepairRecords.length })}
                    onClick={() => setTraceabilityDialogOpen(true)}
                  >
                    <Eye className="size-3.5" />
                    <span className="hidden sm:inline">{t("requirements.traceProof")}</span>
                    <span className="hidden rounded border border-border bg-muted px-1.5 py-0.5 font-mono text-[10px] sm:inline">
                      {t("requirements.itemCount", { count: requirementModelRepairRecords.length })}
                    </span>
                  </Button>
                )}
                <ModelPicker
                  value={defaultModel}
                  onValueChange={updateModel}
                  align="end"
                  triggerClassName="bg-card"
                  disabled={!canRunGeneration}
                />
                <Button
                  type="button"
                  onClick={() => runGenerateDiagrams()}
                  disabled={
                    selectedDiagrams.length === 0 ||
                    generating ||
                    Boolean(requirementReviewBlockedReason) ||
                    Boolean(selectedTargetBlockReason) ||
                    !canRunGeneration
                  }
                  title={
                    !canRunGeneration
                      ? generationBlockedByPermissionReason
                      : selectedTargetBlockReason ?? generationBlockedTitle
                  }
                  className="inline-flex h-9 min-w-0 flex-1 items-center gap-2 px-3 text-sm hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40 sm:flex-none sm:px-4"
                >
                  {generating ? (
                    <Loader2 className="size-4 animate-spin" />
                  ) : (
                    <Wand2 className="size-4" />
                  )}
                  <span className="min-w-0 truncate">{generateDiagramsButtonLabel}</span>
                </Button>
              </div>
            </div>
            {requirementReviewBlockedReason && (
              <Alert className="flex items-center gap-1.5 border px-3 py-2 text-xs">
                <AlertTriangle className="size-3.5" />
                {visibleRequirementReviewBlockedReason}
              </Alert>
            )}

            <MobileCompactGrid
              minWidth={720}
              variant="model-targets"
            >
              {DIAGRAM_ORDER.map((diagram) => {
                const meta = DIAGRAM_META[diagram];
                const localizedLabel = getDiagramLabel(diagram, t);
                const localizedDescription = getDiagramDescription(diagram, t);
                const {
                  autoFillLabels,
                  blockReason,
                  canSelectDiagram,
                  checked,
                  hasPendingAutoReview,
                  isAnalysisDiagram,
                  linkedRules,
                  pendingAutoReviews,
                  sourceCount,
                } = requirementTargetCardState({
                  autoGeneratedUpstreamReviews,
                  canEditRequirements,
                  diagram,
                  generatedDiagrams,
                  hasRequirementSourceText,
                  isRulesStale,
                  rules,
                  selectedDiagrams,
                  staleDiagrams,
                });
                const localizedAutoFillLabels = autoFillLabels.map((label) =>
                  label === DIAGRAM_META.usecase.label
                    ? getDiagramLabel("usecase", t)
                    : label === "需求规则"
                      ? t("requirements.autoFillSources.rules")
                      : t("requirements.autoFillSources.mapping"),
                );
                const DiagramIcon = REQUIREMENT_DIAGRAM_ICON[diagram];
                return (
                  <ModelBentoCard
                    key={diagram}
                    label={localizedLabel}
                    english={meta.english}
                    description={localizedDescription}
                    icon={DiagramIcon}
                    selected={checked}
                    disabled={!canSelectDiagram}
                    countLabel={sourceCount}
                    pendingReview={hasPendingAutoReview}
                    title={
                      !canEditRequirements ? editBlockedReason : undefined
                    }
                    ariaLabel={t(checked ? "requirements.cancelSelect" : "requirements.select", { label: localizedLabel })}
                    checkboxLabel={localizedLabel}
                    onSelectedChange={(value) => toggleDiagram(diagram, value)}
                    status={requirementStatusFor(diagram)}
                    content={
                      <div className="space-y-1.5">
                        {!canSelectDiagram && (
                          <div className="flex items-center gap-1.5 text-destructive">
                            <AlertTriangle className="size-3.5 shrink-0" />
                            <span>
                              {blockReason ??
                                (isAnalysisDiagram
                                  ? t("requirements.useCaseRequired")
                                  : t("requirements.rulesRequired"))}
                            </span>
                          </div>
                        )}
                        {isAnalysisDiagram &&
                          canSelectDiagram &&
                          linkedRules.length === 0 && (
                            <div className="text-muted-foreground">
                              {t("requirements.analysisDependency")}
                            </div>
                          )}
                        <RequirementModelCardPopovers
                          autoFillLabels={blockReason ? [] : localizedAutoFillLabels}
                          label={localizedLabel}
                          linkedRules={linkedRules}
                          pendingAutoReviews={pendingAutoReviews}
                          onDecideAutoReviews={decideAutoReviews}
                          onLocateRule={locateRequirementRule}
                          showRuleLocations={view !== "models"}
                        />
                      </div>
                    }
                  />
                );
              })}
            </MobileCompactGrid>
            <p className="pb-4 text-center text-xs text-muted-foreground">
              {t("requirements.selectionHint")}
            </p>
          </section>}
      </PageContainer>

      {view !== "models" && <RequirementReviewDialog
        generating={generating}
        onConfirmQualityHint={confirmRequirementQualityHint}
        onDecideReviewCandidate={decideRequirementReviewCandidate}
        onOpenChange={(open) => {
          if (!open) setHintDetailRuleId(null);
        }}
        onRepairRequirementRule={repairRequirementRule}
        visibleHintDetail={visibleHintDetail}
      />}

      <RequirementTraceabilityDialogs
        modelRepairResult={modelRepairResult}
        records={requirementModelRepairRecords}
        setModelRepairResult={setModelRepairResult}
        setTraceabilityDialogOpen={setTraceabilityDialogOpen}
        traceabilityDialogOpen={traceabilityDialogOpen}
      />

      {view !== "models" && <Dialog
        open={ruleReplacementDialogOpen}
        onOpenChange={setRuleReplacementDialogOpen}
      >
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>{t("requirements.replace.title")}</DialogTitle>
            <DialogDescription>
              {t("requirements.replace.description", { count: rules.length })}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="gap-2 sm:gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => setRuleReplacementDialogOpen(false)}
            >
              {t("requirements.replace.cancel")}
            </Button>
            <Button
              type="button"
              onClick={confirmRuleReplacement}
              disabled={generating || !canRunGeneration}
            >
              {t("requirements.replace.confirm")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>}

      {view !== "models" && <NewRequirementRuleDialog
        canEditRequirements={canEditRequirements}
        generating={generating}
        newRuleCanSubmit={newRuleCanSubmit}
        newRuleCategory={newRuleCategory}
        newRuleDiagrams={newRuleDiagrams}
        newRuleError={newRuleError}
        newRuleText={newRuleText}
        onCategoryChange={(category) => {
          setNewRuleCategory(category);
          setNewRuleError(null);
        }}
        onOpenChange={(open) => {
          setNewRuleDialogOpen(open);
          if (!open) resetNewRuleForm();
        }}
        onSubmit={submitNewRule}
        onTextChange={(text) => {
          setNewRuleText(text);
          setNewRuleError(null);
        }}
        onToggleDiagram={(diagram, checked) => {
          toggleNewRuleDiagram(diagram, checked);
          setNewRuleError(null);
        }}
        open={newRuleDialogOpen}
      />}

    </div>
  );
}

export function SystemRequirementsPage() {
  return <TextRequirementView view="system" />;
}

export function RequirementsModelPage() {
  return <TextRequirementView view="models" />;
}
