import { SidebarProvider } from '../shared/ui/sidebar';
import { TooltipProvider } from '../shared/ui/tooltip';
import type { ReactNode } from "react";
import { AppI18nProvider } from "../app/providers/i18n-provider";
import { ThemeProvider } from "../shared/ui/theme-provider";
import type {
  AtomicRequirement,
  RequirementBaseline,
  RunSnapshot,
} from "@uml-platform/contracts";
import { feasibilityInputsSchema, buildAcceptedRequirementSnapshot, feasibilityBusinessFlowArtifactSchema } from "@uml-platform/contracts";
import type { RequirementRule } from "../entities/requirement-rule/model";
import type { WorkspaceRecord } from "../entities/workspace/model";
import { WorkspaceShellProvider } from "../features/workspace-shell/state";
import { WorkspaceSessionProvider } from "../features/workspace-session/state";
import { WorkspaceRepositoryProvider } from "../services/workspace-repository";
import type { WorkspaceRepository } from "../services/workspace-repository";
import type { DiagramType } from "../entities/diagram/model";
import { DEFAULT_USER_SETTINGS, USER_SETTINGS_STORAGE_KEY } from "../shared/lib/user-settings";
import { FeedbackDialogProvider } from "../shared/ui/feedback-dialog";

export function createBusinessFlowArtifact(rules: unknown = [createRule()], baseline: unknown = null) {
  const source = buildAcceptedRequirementSnapshot(rules, baseline);
  return feasibilityBusinessFlowArtifactSchema.parse({
    model: { diagramKind: "activity", modelId: "feasibility-business-flow", title: "业务与系统流程图", summary: "处理业务规则", notes: [],
      swimlanes: [{ id: "system", name: "系统" }],
      nodes: [{ id: "start", type: "start" }, { id: "process", type: "activity", name: "处理业务", actorOrLane: "system", input: [], output: [] }, { id: "end", type: "end" }],
      relationships: [{ id: "e1", type: "control_flow", sourceId: "start", targetId: "process" }, { id: "e2", type: "control_flow", sourceId: "process", targetId: "end" }] },
    traceability: [{ requirementId: source.rules[0]!.id, targetId: "process", targetKind: "node" }],
    plantUml: { diagramKind: "activity", modelId: "feasibility-business-flow", source: "@startuml\nstart\n:处理业务;\nstop\n@enduml" },
    svg: { diagramKind: "activity", modelId: "feasibility-business-flow", svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="100"><text>业务流程</text></svg>',
      renderMeta: { engine: "test", generatedAt: "2026-07-19T00:00:00.000Z", sourceLength: 45, durationMs: 1 } },
    fingerprint: source.snapshot.fingerprint,
  });
}

export function createWorkspaceRecord(
  overrides: Partial<WorkspaceRecord> = {},
): WorkspaceRecord {
  return {
    id: "workspace-test",
    name: "Test Workspace",
    requirementText: "",
    selectedDiagramTypes: [],
    rules: [],
    requirementBaseline: null,
    requirementQualityReport: null,
    requirementReviewCandidates: {},
    autoGeneratedUpstreamReviews: {},
    models: {},
    requirementModelTraceability: [],
    generatedDiagramTypes: [],
    plantUml: {},
    svgArtifacts: {},
    diagramErrors: {},
    selectedDesignDiagramTypes: [],
    designModels: {},
    designModelTraceability: [],
    generatedDesignDiagramTypes: [],
    designPlantUml: {},
    designSvgArtifacts: {},
    designDiagramErrors: {},
    manualModelEditStatus: {},
    codeSpec: null,
    codeBusinessLogic: null,
    codeFiles: {},
    codeEntryFile: null,
    codeDependencies: {},
    codeUiMockup: null,
    codeAgentPlan: [],
    codeSkills: [],
    codeSkillDiagnostics: [],
    codeSkillResourcePlan: null,
    codeSkillContext: null,
    codeDiagnostics: [],
    testGenerationResult: null,
    requirementInputFingerprint: null,
    diagramInputFingerprints: {},
    designInputFingerprints: {},
    feasibilityInputs: feasibilityInputsSchema.parse({}),
    feasibilityContextModel: null,
    feasibilityBusinessFlow: null,
    feasibilityContextTraceability: [],
    feasibilityContextPlantUml: "",
    feasibilityContextSvg: "",
    feasibilityContextFingerprint: null,
    feasibilityImplementationPlan: null,
    feasibilityImplementationFingerprint: null,
    rulesVersion: 0,
    rulesBasedOnTextVersion: null,
    diagramVersions: {},
    currentStage: null,
    runStatus: "idle",
    runProgress: 0,
    runMessage: null,
    errorMessage: null,
    ...overrides,
  };
}

export function createRule(
  overrides: Partial<RequirementRule> = {},
): RequirementRule {
  return {
    id: "r1",
    category: "业务规则",
    text: "用户必须登录后才能访问主要功能。",
    relatedDiagrams: ["usecase"],
    ...overrides,
  };
}

export function createRequirementBaseline(
  overrides: Partial<RequirementBaseline> = {},
): RequirementBaseline {
  const requirement: AtomicRequirement = {
    id: "REQ-001",
    sourceRuleId: "r1",
    sourceFragment: "用户必须登录后才能访问主要功能。",
    type: "functional",
    actor: "用户",
    subject: "用户",
    action: "访问",
    object: "主要功能",
    condition: "用户已登录",
    outcome: "系统允许访问主要功能",
    confidence: 0.9,
    status: "accepted",
    criticality: "high",
    acceptanceCriteria: ["用户登录后可以访问主要功能。"],
    fieldProvenance: {},
  };
  return {
    runId: "run-baseline",
    sourceDocumentId: "inline-requirement",
    createdAt: "2026-06-05T00:00:00.000Z",
    requirements: [requirement],
    assumptions: [],
    conflicts: [],
    qualityReport: {
      runId: "run-baseline",
      status: "passed",
      summary: "需求基线已确认。",
      issues: [],
      blockingIssueIds: [],
      reviewRequiredRequirementIds: [],
    },
    ...overrides,
  };
}

export function createRunSnapshot(
  overrides: Partial<RunSnapshot> = {},
): RunSnapshot {
  return {
    runId: "run-test",
    requirementText: "",
    selectedDiagrams: [],
    analysisTargetUseCaseIds: [],
    rules: [],
    requirementBaseline: null,
    coverageMatrix: null,
    traceabilityMatrix: null,
    models: [],
    requirementModelTraceability: [],
    plantUml: [],
    svgArtifacts: [],
    diagramErrors: {},
    requirementTrace: [],
    currentStage: "render_svg",
    status: "completed",
    error: null,
    ...overrides,
  };
}

export function withWorkspaceProviders(
  children: ReactNode,
  repository?: WorkspaceRepository,
) {
  if (!localStorage.getItem(USER_SETTINGS_STORAGE_KEY)) {
    localStorage.setItem(
      USER_SETTINGS_STORAGE_KEY,
      JSON.stringify(DEFAULT_USER_SETTINGS),
    );
  }

  return (
    <AppI18nProvider>
      <ThemeProvider>
        <FeedbackDialogProvider>
          <WorkspaceShellProvider>
            <WorkspaceRepositoryProvider repository={repository}>
              <WorkspaceSessionProvider><SidebarProvider><TooltipProvider>{children}</TooltipProvider></SidebarProvider></WorkspaceSessionProvider>
            </WorkspaceRepositoryProvider>
          </WorkspaceShellProvider>
        </FeedbackDialogProvider>
      </ThemeProvider>
    </AppI18nProvider>
  );
}

export function createDiagramVersions(
  entries: Array<[DiagramType, number]>,
): Partial<Record<DiagramType, number>> {
  return Object.fromEntries(entries) as Partial<Record<DiagramType, number>>;
}
