// Exercises saved platform requirements through MCP snapshots, real implementation evidence and local execution.
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import test, { type TestContext } from "node:test";
import {
  designInputFingerprint,
  snapshotInputFingerprint,
  mcpImplementationReportSchema,
  mcpImplementationSnapshotSchema,
  type AtomicRequirement,
  type McpImplementationReport,
  type McpScope,
} from "@uml-platform/contracts";
import { buildContext } from "./implementation-context.js";
import { withImplementationArtifacts } from "./implementation-artifacts.js";
import { contentHash } from "./source-artifacts.js";

const whole: McpScope = { requirementIds: [], artifactIds: [] };
const projectId = "library-implementation";
const sha = (value: Buffer) => `sha256:${createHash("sha256").update(value).digest("hex")}`;
type Assessment = {
  overall: string;
  verificationAuthority: string;
  issues: Array<{ code: string; severity: string }>;
  entries: Array<{ taskId: string; status: string; issues: Array<{ code: string; severity: string }>; checks: Array<{ status: string }> }>;
};
type Verify = (input: { root: string; snapshot: unknown; report: unknown; runChecks?: boolean }) => Promise<Assessment>;

function savedState(limit = 5) {
  const requirementText = `每位读者最多同时借阅${limit}本书，归还后可继续借阅；拒绝借阅不能增加已借数量。`;
  const rule = { id: "BORROW-RULE", category: "业务规则", text: requirementText, relatedDiagrams: ["class"] };
  const requirement: AtomicRequirement = {
    id: "BORROW", sourceRuleId: rule.id, sourceFragment: requirementText, type: "business-rule", actor: "读者", subject: "借阅服务",
    action: "借阅", object: "图书", condition: `已借数量少于${limit}本`, outcome: "借阅成功后数量增加1", confidence: 1,
    status: "accepted", criticality: "high", acceptanceCriteria: [
      `第${limit}本可以借阅，第${limit + 1}本必须被拒绝。`,
      "拒绝借阅后已借数量不变。", "归还一本后可以再次借阅。",
    ], fieldProvenance: { acceptanceCriteria: { source: "source-text", status: "accepted" } },
  };
  const qualityReport = { runId: "requirements-run", status: "passed", summary: "借阅约束已确认", issues: [], blockingIssueIds: [], reviewRequiredRequirementIds: [] };
  const analysis = {
    diagramKind: "class", modelId: "borrow-domain", title: "借阅领域", summary: "图书借阅概念", notes: [],
    classes: [{ id: "loan", name: "Loan", attributes: [], operations: [] }], interfaces: [], enums: [], relationships: [],
  };
  const design = {
    diagramKind: "class", modelId: "borrow-implementation", title: "借阅服务设计", summary: "管理每位读者的借阅集合", notes: [],
    classes: [{ id: "loan-service", name: "LoanService", attributes: [], operations: [], constraints: [`最多同时借阅${limit}本`] }], interfaces: [], enums: [], relationships: [],
  };
  const sourceRef = { modelId: analysis.modelId, diagramKind: "class", elementId: "loan", elementKind: "class", label: "Loan" };
  const targetRef = { modelId: design.modelId, diagramKind: "class", elementId: "loan-service", elementKind: "class", label: "LoanService" };
  const requirementTrace = [{ ruleId: rule.id, target: sourceRef, reviewStatus: "confirmed" }];
  const fingerprint = snapshotInputFingerprint({ requirementText, rules: [rule] });
  return {
    requirementText, rules: [rule],
    requirementBaseline: { runId: "requirements-run", sourceDocumentId: "requirements-document", requirements: [requirement], assumptions: [], conflicts: [], qualityReport, createdAt: "2026-01-01T00:00:00Z" },
    models: { "borrow-domain": analysis }, designModels: { "borrow-implementation": design },
    plantUml: { "borrow-domain": "@startuml\nclass Loan\n@enduml" },
    designPlantUml: { "borrow-implementation": `@startuml\nclass LoanService\nnote right of LoanService : 最多同时借阅${limit}本\n@enduml` },
    requirementModelTraceability: requirementTrace,
    designModelTraceability: [{ source: sourceRef, targets: [targetRef], reviewStatus: "confirmed" }],
    requirementInputFingerprint: fingerprint, diagramInputFingerprints: { "borrow-domain": fingerprint },
    designInputFingerprints: { "borrow-implementation": designInputFingerprint([analysis], requirementTrace) },
    autoGeneratedUpstreamReviews: {
      analysis: { artifactId: "borrow-domain", artifactType: "requirement-model", status: "confirmed" },
      design: { artifactId: "borrow-implementation", artifactType: "design-model", status: "confirmed" },
    },
  };
}

function distributed(state = savedState(), scope = whole) {
  const original = buildContext(state, scope);
  const context = withImplementationArtifacts(original, projectId);
  const bundle = context.artifacts.find((artifact) => artifact.id === "implementation:bundle")!;
  const validator = context.artifacts.find((artifact) => artifact.id === "implementation:validator")!;
  const snapshot = mcpImplementationSnapshotSchema.parse(bundle.payload.snapshot);
  const report = mcpImplementationReportSchema.parse(bundle.payload.reportTemplate);
  assert.equal(typeof validator.payload.source, "string");
  return { original, context, bundle, validator, snapshot, report };
}

function implementation(limit: number) {
  return [
    "export class LoanService {",
    "  #loans = new Set();",
    "  get count() { return this.#loans.size; }",
    `  borrow(book) { if (this.#loans.size >= ${limit}) throw new Error('borrowing limit'); this.#loans.add(book); }`,
    "  returnBook(book) { this.#loans.delete(book); }",
    "}",
  ].join("\n");
}
function acceptanceTests(limit: number) {
  return [
    "import assert from 'node:assert/strict';",
    "import test from 'node:test';",
    "import { LoanService } from '../src/loan-service.mjs';",
    "test('borrowing boundary, rejection integrity and restored capacity', () => {",
    "  const service = new LoanService();",
    `  for (let number = 1; number <= ${limit}; number++) service.borrow('book-' + number);`,
    `  assert.equal(service.count, ${limit});`,
    "  assert.throws(() => service.borrow('extra'), /borrowing limit/);",
    `  assert.equal(service.count, ${limit});`,
    "  service.returnBook('book-1');",
    `  assert.equal(service.count, ${limit - 1});`,
    "  service.borrow('replacement');",
    `  assert.equal(service.count, ${limit});`,
    "});",
  ].join("\n");
}
async function localRepository(t: TestContext, source: string) {
  const tempParent = path.resolve(tmpdir());
  const root = await mkdtemp(path.join(tempParent, "uml-implementation-e2e-"));
  t.after(async () => {
    // Cleanup is confined to the isolated temporary repository created by this test.
    assert.equal(path.dirname(path.resolve(root)), tempParent);
    assert.match(path.basename(root), /^uml-implementation-e2e-/);
    await rm(root, { recursive: true, force: true });
  });
  await mkdir(path.join(root, "src"));
  await mkdir(path.join(root, "test"));
  await writeFile(path.join(root, "package.json"), '{"private":true,"type":"module"}');
  const verifierPath = path.join(root, "uml-verify.mjs");
  // Execute exactly the source handed to an external agent, without importing the API implementation directly.
  await writeFile(verifierPath, source);
  const { verifyImplementation: verify } = await import(pathToFileURL(verifierPath).href) as { verifyImplementation: Verify };
  return { root, verify };
}
async function writeImplementation(root: string, codeLimit: number, testLimit: number) {
  await writeFile(path.join(root, "src/loan-service.mjs"), implementation(codeLimit));
  await writeFile(path.join(root, "test/loan-service.test.mjs"), acceptanceTests(testLimit));
}
async function implementedReport(root: string, source: ReturnType<typeof distributed>): Promise<McpImplementationReport> {
  const report = structuredClone(source.report);
  const task = source.snapshot.tasks[0];
  const entry = report.entries.find((candidate) => candidate.taskId === task.id)!;
  const criterionIds = task.acceptanceCriteria.map((criterion) => criterion.id);
  entry.status = "implemented";
  entry.plannedTargets = [{ path: "src/loan-service.mjs", responsibility: "落实借阅上限、拒绝一致性与归还后额度恢复" }];
  entry.designRefs = [task.designRefs.find((ref) => ref.elementId === "loan-service")!];
  entry.actualRefs = [{ path: "src/loan-service.mjs", symbol: "LoanService", contentHash: sha(await readFile(path.join(root, "src/loan-service.mjs"))) }];
  entry.inputRefs = [{ path: "package.json", contentHash: sha(await readFile(path.join(root, "package.json"))) }];
  entry.testRefs = [{ path: "test/loan-service.test.mjs", criterionIds, contentHash: sha(await readFile(path.join(root, "test/loan-service.test.mjs"))) }];
  entry.checks = [
    { id: "syntax", kind: "engineering", command: process.execPath, args: ["--check", "src/loan-service.mjs"], criterionIds: [] },
    { id: "borrowing-acceptance", kind: "behavior", command: process.execPath, args: ["--test", "test/loan-service.test.mjs"], criterionIds },
  ];
  return mcpImplementationReportSchema.parse(report);
}

test("distributed snapshot and template bind real saved sources without recursive manifests or unstable versions", () => {
  const state = savedState();
  const before = structuredClone(state);
  const first = distributed(state);
  const second = distributed(structuredClone(state));
  assert.deepEqual(state, before);
  assert.deepEqual(first.context, second.context);
  assert.equal(first.snapshot.contextVersion, first.context.version);
  assert.equal(first.report.contextVersion, first.context.version);
  assert.deepEqual(first.context.manifest, first.original.manifest);
  assert.ok(first.snapshot.manifest.every((source) => !source.artifactId.startsWith("implementation:")));
  assert.ok(first.snapshot.tasks.every((task) => task.sourceArtifactIds.every((id) => !id.startsWith("implementation:"))));
  assert.deepEqual(first.snapshot.tasks.map((task) => task.id), ["implement:requirement:BORROW"]);
  assert.equal(first.snapshot.tasks[0].acceptanceCriteria.length, 3);
  assert.deepEqual(first.snapshot.tasks[0].issues.filter((issue) => issue.severity === "blocking"), []);
  assert.deepEqual(first.report.entries.map((entry) => entry.status), ["planned"]);
  assert.ok(first.report.entries.every((entry) => !entry.actualRefs.length && !entry.testRefs.length && !entry.checks.length));
  assert.equal((first.bundle.payload.reportSchema as { type: string }).type, "object");
  assert.equal(first.bundle.version.contentHash, contentHash(first.bundle.payload));
  assert.equal(first.validator.version.contentHash, contentHash(first.validator.payload));
  const incidentalUi = withImplementationArtifacts(buildContext({ ...state, activeTab: "design", progress: 0.8 }, whole), projectId);
  assert.equal(incidentalUi.version, first.context.version);
  assert.ok(first.snapshot.manifest.some((source) => source.artifactId === "requirements:source" && source.freshness === "unknown"));
});

test("partial request scope keeps shared-rule dependencies as sources without adding implementation tasks", () => {
  const state = savedState();
  const second: AtomicRequirement = { ...state.requirementBaseline.requirements[0], id: "RETURN", sourceFragment: "归还操作需要保存记录", acceptanceCriteria: ["归还成功后有一条归还记录"] };
  state.requirementBaseline.requirements.push(second);
  const source = distributed(state, { requirementIds: ["BORROW"], artifactIds: [] });
  assert.ok(source.snapshot.manifest.some((item) => item.artifactId === "requirement:RETURN"));
  assert.deepEqual(source.snapshot.tasks.map((task) => task.id), ["implement:requirement:BORROW"]);
  assert.deepEqual(source.report.entries.map((entry) => entry.taskId), ["implement:requirement:BORROW"]);
  assert.ok(source.snapshot.tasks[0].sourceArtifactIds.includes("requirement:RETURN"));
});

test("saved five-book requirement verifies real code and tests despite explicitly unknown raw-source freshness", async (t) => {
  const source = distributed();
  const local = await localRepository(t, source.validator.payload.source as string);
  await writeImplementation(local.root, 5, 5);
  const report = await implementedReport(local.root, source);
  const result = await local.verify({ root: local.root, snapshot: source.snapshot, report, runChecks: true });
  assert.equal(result.overall, "verified", JSON.stringify(result));
  assert.equal(result.verificationAuthority, "local-execution");
  assert.deepEqual(result.entries[0].checks.map((check) => check.status), ["passed", "passed"]);
  assert.ok(result.entries[0].issues.some((issue) => issue.code === "unknown_freshness" && issue.severity === "warning"));
  await writeImplementation(local.root, 6, 5);
  const incorrectReport = await implementedReport(local.root, source);
  const incorrect = await local.verify({ root: local.root, snapshot: source.snapshot, report: incorrectReport, runChecks: true });
  assert.equal(incorrect.overall, "failed", JSON.stringify(incorrect));
  assert.deepEqual(incorrect.entries[0].checks.map((check) => check.status), ["passed", "failed"]);
});

test("changing saved requirement to eight invalidates previous evidence and requires matching code and acceptance updates", async (t) => {
  const before = distributed(savedState(5));
  const local = await localRepository(t, before.validator.payload.source as string);
  await writeImplementation(local.root, 5, 5);
  const oldReport = await implementedReport(local.root, before);
  assert.equal((await local.verify({ root: local.root, snapshot: before.snapshot, report: oldReport, runChecks: true })).overall, "verified");

  const after = distributed(savedState(8));
  assert.notEqual(after.snapshot.contextVersion, before.snapshot.contextVersion);
  assert.notEqual(after.snapshot.manifest.find((source) => source.artifactId === "requirement:BORROW")!.contentHash, before.snapshot.manifest.find((source) => source.artifactId === "requirement:BORROW")!.contentHash);
  assert.ok(after.snapshot.tasks[0].acceptanceCriteria.some((criterion) => criterion.text.includes("第8本") && criterion.text.includes("第9本")));
  const stale = await local.verify({ root: local.root, snapshot: after.snapshot, report: oldReport, runChecks: true });
  assert.equal(stale.overall, "stale", JSON.stringify(stale));
  assert.deepEqual(stale.entries[0].checks, []);

  await writeImplementation(local.root, 5, 8);
  const updatedTests = await implementedReport(local.root, after);
  const stillWrong = await local.verify({ root: local.root, snapshot: after.snapshot, report: updatedTests, runChecks: true });
  assert.equal(stillWrong.overall, "failed", JSON.stringify(stillWrong));

  await writeImplementation(local.root, 8, 8);
  const newReport = await implementedReport(local.root, after);
  assert.notEqual(newReport.entries[0].actualRefs[0].contentHash, oldReport.entries[0].actualRefs[0].contentHash);
  assert.notEqual(newReport.entries[0].testRefs[0].contentHash, oldReport.entries[0].testRefs[0].contentHash);
  assert.notDeepEqual(newReport.entries[0].sourceVersions, oldReport.entries[0].sourceVersions);
  const completed = await local.verify({ root: local.root, snapshot: after.snapshot, report: newReport, runChecks: true });
  assert.equal(completed.overall, "verified", JSON.stringify(completed));
  assert.deepEqual(completed.entries[0].checks.map((check) => check.status), ["passed", "passed"]);
});
